# Acknowledgments {-}

I would like to thank Bruno Hérault and Stéphane Traissac for their guidance and advice during the whole internship. I congratulate Bruno to have been able to communicate and be reactive besides his numerous recent travels. I am grateful to Bruno and Camille Piponiot to have introduced me to the wonderful world of Bayesian statistics. All this work would not have been possible without TROLL model and the whole team that works on it : Jérôme Chave, Isabelle Maréchaux and Fabian Fischer. I thank all of the team to have introduced me to the model and guide me in its development from the opposite side of the Atlantic. I would also like to thank Laurent Descroix and people from National Forest Office who introduced me to sylviculture from french Guiana and helped me to build a realistic forest model. I also thank Aurélie Dourdain for her help to access Paracou data, Éric Marcon for his advice on biodiversity analysis, and Pascal Padolus for his patience and help wiht Tabebuia cluster. The study would not have been possible without Pascal Petronelli and all people who have contributed to Paracou and Guyafor data collection over the years. Finally I am grateful to Maxime Réjou-Méchain, Raphaël Pélissier, and AMAP colleagues, in addition to Myriam Heuertz and BIOGECO colleagues and Aurélie Cuvelier who helped me discuss the study results and build the present master thesis. To conclude, I thank everybody that played a role more or less important in the development of my internship and that I might have forgotten.
