# Introduction {-}

Tropical forests disturbances, through deforestation and degradation, account for 8.26 billion of tons of carbon dioxyde emissions per year [@Pearson2017]. It represents the third source of greenhouse gas. Besides deforestation has been rightly the focus of worldwide attention, degradation has been less studied and quantified through tropics. Degradation from forest has been estimated to represents 10 time deforestation [@Herold2011] and represents 20% of greenhouse gas emissions in the brazilian Amazon [@Asner2005]. Degradation has met numerous definitions [@Simula2009], but can be defined as the result from a disturbance event that induced a modification of the forest ecosystem reducing ecosystem services while keeping the ecosystem as a forest, contrary to deforestation.

Sutainable forest management in the tropics (i.e. managed selective harvesting of timber) has been widely promoted internationnaly to combat tropical deforestation and degradation [@Zimmerman2012]. Currently logging from tropical forests accounts for one eight of global timber production [@Blaser2011] and is still increasing. Most tropical timber production originates from selective logging, the targeted harvesting of timber from commercial species in a single cutting cycle [@Martin2015].

On the other hand, tropical rainforests have fascinated ecologists due to their outstanding diversity [@connell_diversity_1978]. Effectively tropical forests host over half of the Earth's biodiversity [@Scheffers2012]. High biodiversity from tropical rainforests is the source of many ecosystem functions. Amongst others, tropical forests play a key role in biogeochemical cycles, including carbone storage [@Lewis2004]. Ecosystem functions from tropical forests support numerous ecosystem services, such as timber production and climate regulation. 

But several authors argue that selective logging represents a major threat to biodiversity [@Carreno-Rocabado2012; @DeAvila2015; @Gibson2013; @Martin2015; @Zimmerman2012], challenging the sustainable definition from current selective logging. We consequently need to assess both short and long term impacts of selective logging on tropical forest ecosystems to implement better sylvicultural practices in order to reach sustainability.

The question of selective logging impact on tropical forest can be directly related to the emerging field of biodiversity and ecosystem functionning [@Loreau2000]. Tropical forest outstanding biodiversity will be both a factor and a result of forest ecosystem response to logging disturbance. And forest ecosystem response to logging disturbance will directly modify ecosystem functionning in both short and long term. Consequently assessing selective logging effect on tropical forest linking diversity and ecosystem functionning seems an obvious and promising way [@Loreau2010].

Negative short term impacts of selective logging have been assessed [@Carreno-Rocabado2012; @DeAvila2015;  but see @Martin2015]. Much less is known about the long term impact [@Osazuwa-Peters2015]. The main reason is the difficulty to conduct long term empirical study [but see @Herault2010], which can be completed by the use of forest simulators [@Huth2004; @Khler2004; @Ruger2008; @Tietjen2006]. Individual-based models of forest dynamics present the perfect framework to develop such joint biodiversity-ecosystem approaches [@Li]. Individual-based models describe forest accumulating carbon through time, assessing tree growth, or releasing carbon through gap opening [@Bugmann2001]. Up to several dozens of different Plant Functional Types (PFTs) are generally defined and models can sometimes be fully spatially explicit [@Pacala1996]. Recently, the forest growth simulator TROLL [@Chave1999], an individual-based and spatially explicit forest model, was developped to introduce recent advances in plant physiological community. TROLL model relates physiological processes to species-specific functional traits [@Li]. Consequently, TROLL model allow to simulate fully a neotropical forest biodiversity to study biodiversity-ecosystem functionning link response to logging disturbance.

We decided to use the forest model TROLL to study the role of biodiversity in forest ecosystem answer to disturbance. Resilience encompass several definitions but was summarized by @Oliver2015 as the degree of resistance or fast recovery from an ecosystem function to environmental disturbance.

Our work is based on the general hypothesis of a positive relationships between biodiversity and productivity. We assumed that when a disturbance event happen, due to a higher productivity, forest with an increased diversity will recover quicker and thus be more resilient. This theoritical expectation stand on two processes: complementarity and selection effects [@Loreau2001]. If we take a species pool with different productivity in monoculture. Their assemblage will allow theim an overall higher productivity due to a better ressources acquisition through ressources partitionning and niche differentiation. Additionnally, some species will individually have an higher productivity in the assemblage than in monoculture due to facilitation from other species present in the assemblage. Complementarity effect is the addition of the better ressource acquisition and the facilitation. Now if we look at the evolution of the species assemblage over time, more competitive species will progressively dominate through competitive selection. And if competitive species are more productive, they will increase assemblage overall productivity. This ressources preemption by more competitive species is the selection effect. Moreover, we expect the sampling effect to improve more diverse forest. A bigger initial sampling of the regional species pool in a rich forest, will allow more redundancy and a lower risk to lose important functional traits assemblages for the ecosystem when the disturbance happen.

Generally, positive relationship between biodiversity and productivity were emprically and experimentally demonstrated on grassland systems [@Hooper2005a; @Loreau2001a; @Naeem2002]; but few studies focused on the case of tropical forests. One of the few studies was realized by @Chisholm2013 and has shown a positive significative relationship between species richness and wood productivity on a worlwide forest network. But those study still presents three major limits: (1) study time are inferior to a tree life time, (2) experimental network include scarcely disturbed plot, and (3) correlative approach does not explain mechanisms involved in the relationship.

In the present study, we focused on mechanisms involved in the relationship between biodiversity and forest ecosystem resilience. We used a simulation approach using TROLL model to assess long term processes for different types and levels of disturbances. We first assessed diversity effect on forest resilience of structure and functionning using numerous indices of taxonomic and functional diversities. Then, we measured biodiversity net effect, partitioned into complementarity and selection effects, resilience for several ecosystem metrics.

