# Material and Methods

## Sensitivity analysis

@Li already assessed TROLL model sensitivity to several parameters ($k$ see \@ref(eq:PPFD), $\phi$ see \@ref(eq:LCP), $g1$ see \@ref(eq:gs), $f_{wood}$ see \@ref(eq:DeltaV), $f_{canopy}$ see \@ref(eq:DeltaLA) and $m$ see \@ref(eq:db)) which they assumed having a key role in model functioning.

On the other hand, we decided to use TROLL to study resistance and resilience of ecosystem face to disturbance, highlighting the role of biodiversit. Consequently we particulrarly needed to assess the importance of functional traits to further better control and evaluate functional diversities. We also needed to assess the sensitivity of TROLL model to the seed rain constant ($n_{ext}$, see \@ref(eq:next)) because we assume it is one of the main factor of tree recruitments after disturbance in simulations.

TROLL model currenty uses leaf mass per area ($LMA$ in $g.m^{-2}$), leaf nitrogen content per dry mass ($N_m$ in $mg.g^{-1}$), leaf phosphorus content per dry mass ($P_m$ in $mg.g^{-1}$), wood specific gravity ($wsg$ in $g.cm^{-3}$), diameter at breasth height threshold ($dbh_{thresh}$ in $m$), asymptotic height ($h_{lim}$ in $m$), and parameter of the tree-height-dbh allometry ($a_h$ in $m$). To assess the sensitivity of TROLL model to species functionnal traits, we performed a sensitivity analysis by fixing species trait values to their mean. Each trait was tested independently. We reduce to a common mean traits with a Perason's correlation value $r \geq 0.8$ ($h_{max}$ and $a_h$ with a correlation of $r=0.98$).

To assess the sensitivity of TROLL model to seed rain, we performed a sensitivity analysis by fixing simulations seed rain constant to 2, 20, 200 and 2000 seeds per hectare (default value being 200 seeds per hectare).

Simulations were conducted on Intel Xeon(R) with 32 CPUs of 2.00GHz and 188.9 GB of memory. We assumed maturity of the forest after 500 years of regeneration (Maréchaux & Chave) and computed simulation 100 years after a disturbance event with 40% loss of basal area. Due to computer limitations we did not run replicate (besides it should be necessary to reduce simulation stochasticity). To assess ecosystem outputs sensitivity to studied parameters, we compared it to 100 replicates of control simulations with all parameters set to default values. Ecosystem outputs outside of the range of the control replicates values are significantly influenced by the studied parameter.

## Disturbance

*Most tropical timber production originates from selective logging, the targeted harvesting of timber from species of interest. Consequently, tropical sylviculture can be assimilated to a disturbance. The main difference between a disturbance and selective logging is the targetting of both species and individuals of interest. So we decided to first asses unselective disturbance effect on tropical forest ecosystem to subsequently better understand selective logging effect. We first implemented a simple disturbance module inside TROLL model to simulate unselective disturbance.* **Already inside model descripiton !**

We first implemented a disturbance module inside TROLL model to simulate unselective disturbance. 60 tree communities were then defined with different levels of both specific and functional richness to explore the role of biodiversity on tropical forest ecosystem answer to disturbance. Next, different levels of disturbance were simulated on previous mature communities. Finally, resilience of ecosystem major global variables (related to carbon stock, forest dynamic and florisitic structure) from simulations were partitioned between selection effects and niche complementarity [@Loreau2001].

## Selective logging

Once the unselective effect of disturbance on forest ecosystem studied, we can focus on selective logging to highlight the effect of species and individuals targetting on the ecosystem answer. We first implemented a sylviculture module inside TROLL model to simulate selective logging in regards to french Guiana practices. We used the 60 communities from disturbance simulations to study the role of biodiversity in both forest ecosystem and commercial species answer to selective logging. We then 

## Design of experiment

In order to assess the role of biodiversity in ecosystem answer to disturbance, we needed to create a space of experiments encompassing both variation of disturbance, biodiversity and time. Disturbance was represented by percentage of basal area loss (0%, 25%, 50% and 75%). Biodiversity was integrated with two components specific and functional diversities. We used species richness $SR$ to represents species diversity (5, 25, and 125). Functional diversity can be related to numerous components, and @Borgy2017 argued for 5: richness, divergence, regularity, overlap and mean. Because mature forest were created from a bare soil with TROLL simulations, we could not control a priori divergence, regularity and overlap but only assess theim before diturbance. Consequently, we focused on functional richness with convex hull volume $CHV$ and functional mean with community weighted mean $CWM$. For each level of species richness $SR$, we selected 20 communities with growing convex hull volume $CHV$ but with a community weighted means close to the regional species pool community weighted means. Effectivelly, we did not wanted drastic change in community means that could have more effect than functional richness itself. This design of experiments resulted in 60 communities ($5~SR*20~CHV$) and 240 simulations ($60 ~communities*4~levels~of~disturbance$) over 600 years (maturity being assumed after 500 years of regeneration [@Li]). Figure \@ref(fig:DOE) presents the design of experiment for communities biodiversity after the forest mature were simulated, and thus before disturbance. We obtained a broad range of both functionl dispersion $FDis$ and aboveground biomass $AGB$ for simulated forest ecosystems before disturbance.

```{r DOE, echo=FALSE, fig.cap='Experimental design before disturbance. Communities are implemented along a gradient of species richness (SR) and functional dispersion (FDis) resulting in a broad range of aboveground biomass (AGB). FDis was caluclated based on 4 functional traits (leaf mass per area, wood specific gravity, maximum diameter, maximum height).', cache=TRUE}
# Data prep
load('~/Documents/ECOFOG/Results/disturbance/maturity/matureData.Rdata')
data <- datal$time
data <- data[data$time > 450,]
data <- data.frame(apply(data[c('agb','ba','n10','n30')],
                         2, function(x) tapply(x, data$sim, mean)))
data <- cbind(data.frame(sim = row.names(data)), data)
data$richness <- as.factor(floor(as.numeric(as.character(data$sim))))
species <- read.table('~/Documents/ECOFOG/TROLL/inst/extdata/species.txt',
                      header=T, dec=".", sep="",
                      row.names = 1)[c('LMA', 'wsg', 'dmax', 'hmax')]
species <- species[row.names(datal$species),]
fd <- suppressWarnings(FD::dbFD(species, t(datal$species), messages = F))
data <- cbind(data, do.call('cbind',
                            fd[c('FRic', 'FEve', 'FDiv', 'FDis', 'RaoQ')]))
data <- cbind(data, fd$CWM)
rm(fd, species, datal)

# Graph
g <- ggplot(data, aes(x = FDis, y = richness, 
                      label = sim, color = agb/1000)) + 
  geom_point(size = 3) + 
  geom_text_repel() +
  scale_color_continuous("Aboveground\nBiomass\n(AGB, ton C/ha)") +
  xlab("Functional dispersion (FDis)") +
  ylab("Species richness (SR)")

g ; rm(data)
```

## Ecosystem answer anlaysis

Tropical forest ecosystems provides numerous ecosystem services linked to several ecosystem functions. We focused on few functions and related metrics to analyse ecosystem answer to disturbance: carbon stock with aboveground biomass ($AGB$ in $ton~C.ha^{-1}$), forest dynamic with number of stem above $10~cm$ diameter at breast height ($N10$), and floristic composition with **?** (**?** in **?**).

The resilience of metrics values post disturbance were assessed through @Henry2012 formula:

\begin{equation}
  R\left(t\right)=\frac{Recovery\left(t\right)}{Loss\left(t_d\right)} \approx \frac{X(t)}{X(t_d-1)}
  (\#eq:Resilience)
\end{equation}

The resilience of the system $R(t)$ at the time $t$ is described by the ratio of recovery $Recovery(t)$ at time $t$ to loss suffered $Loss(t_d)$ at disturbance time $t_d$. We transformed the equation in the resilience of the system $R(t)$ at the time $t$ being the ratio of the ecosystem metric $X(t)$ at time $t$ to the ecosystem metric before the disturbance happened $X(t_d-1)$ at time $t_d-1$. $X(t_d-1)$ was calculated as the mean of the ecosystem output for 50 last years of the simulation of the mature forest (over 600 years). Then, we calculated for each simulation the recovery time $t_{recovery}$ were the ecosystem reached back its stable state defined as its state before disturbance. But some ecosystem metrics can reach pre disturbance value wihtout revealing ecosystem recovery. For instance, number of stem above $10~cm$ diameter at breast height $N10$ will first decrease due to disturbance. Then $N10$ will exceed its initial value due to new seedlings recruitment before decreasing towards its pre disturbanec value. Consequently, the first time $N10$ reaches back its pre disturbance value can not be considered as the recovery time $t_{recovery}$. In order to solve this issue, we considered the ecosystem as stable again when its whole set of observed metrics reach their pre disturbance values.

Biodiversity is not only a facet of the experimental design and an ecosystem output through florisitic composition, but also interact on ecosystem functioning and consequently on its answer to disturbance. Biodiversity ecosystem functioning relation can be split in complementarity and selection effect with @Loreau2001 partitioning:

\begin{equation}
  \begin{array}{c}
    NE = X_O - X_E = CE + SE \\
    CE = N* \overline{\Delta RX} \overline{M}\\
    SE = N*cov(\Delta RX,M)
  \end{array}
  (\#eq:BiodivPart)
\end{equation}

Biodiversity net effect $NE$ is based on the difference between ecosystem variable $X$ observed value $X_O$ within the community mixture of species and its expected value $X_E$ if species performance were equal to their performance in monocultures. This effect can be partitioned between complementarity effect $CE$, representing niche partitionning, positive interactions, and resource supply, and selectvie effect $SE$ due to dominant species pool driving the ecosystem. Both metrics depend on the variation of relative ecosystem variable $\Delta RX$:

\begin{equation}
  \Delta RX_{sp} = \frac{X_{sp}(mixture)}{X_{sp}(monoculture)} - P_{sp}
  (\#eq:DeltaRY)
\end{equation}

$X_sp$ is the ecosystem variable value for one species either in mixture $X_{sp}(mixture)$ or in monoculture $X_{sp}(monoculture)$. $P_{sp}$ is the proportion of the species in the mixture represented by species relative abundance. Consequently, $CE$ averages diversity effects of all species presents in the mixture (both negatives and positives). Whereas $SE$ become positive when dominant species outperform theimselves in mixture than in monoculture, and negative when less dominant species outperform theimselves in mixture than in monoculture [@Tobner2016].

Recovery trajectories of ecosystem variable after disturbance were partitioned between complementarity effect $CE$ and selection effect $SE$. In order to do that, the design of experiment was repeated for each species indivdually representing 652 simulations of monoculture.
