# Discussion

In the limit of the model, we were able to show that diversity improved tropical forest resilience. More particularly, functional diversity and evenness are key components of diversity in forest recovery after disturbance. Moreover, we found that complementarity between species was insuring forest recovery in forest succession start with facilitation before more productive species dominate the forest and insure recovery. Our results advocates for a sustainable harvesting of tropical forests through an increased resilience due to high diversity. But this conclusion should met a sustainable definiton of selective logging following @Zimmerman2012. Because if the harvesting is not sustainable negative feedbacks will slowly diminish diversity and its benefits for forest resilience, resulting in forest degradation.

## TROLL limits

Belowground processes, herbaceaous plants, epyphytes and lianas are not simulated in TROLL but they not reprensent the only limit of the model. Other processes are simulated but simplified, and we used sensitivity analysis to assess their relative importance. We found that few functional traits were influencing whole forest structure and dynamic. In addition, we found that the seed rain constant had an important effect on species functional composition and diversity. High external seed rain resulted in a quick recovery of the system toward an equilibrium close to the regional species frequency levied by the seed rain. On the contrary, low seed rain let the simulated forest works as a closed system with more system feedback but a lower stability through time with longer species diversity transitions. In order to study the role of diversity in forest resilience we decided to remove the seed rain constant to get a closed system and look at the role of diversity when it maintains itself through feedbacks and not with immigration. 

Finally, sylviculture module implemented inside TROLL showed lacks of ability to reproduce selective logging with current design of experiments. Results did not seem to be usable and will not be discussed. The main issues was the ability of the model to simulate mature forest with correct abundancy of mature trees from commonly harvested species. Two solutions might be possible in the tunning of the model. First, forest inventories could be used to initialize the model instead of a bare soil resulting in realistic species abundances, especially for harvested species. Secondly, selective logging could focus on guilds of species meeting peculiar values of functional traits [as wood density, see @Huth2004; @Khler2004; @Ruger2008] allowing the model to harvest more volume in order to meet reality.

## Diversity improve tropical forest resilience

Our results validated the hypothesis of a significative relationship between forest resilience and functional diversity and evenness ($p < 0.01$ and $p < 0.05$ respectivelly). Thus we were able to show that diversity improve forest resilience. More particularly, functional diversity seems a major aspect of resilience if its strengthened by a high functional evenness. Effectively high functional diversity needs evenness in order to better answer disturbance, if not the diversity is masked by ecosystem dominant species. Those results confirms the review of @Diaz2001 advocating for underevaluated importance of plant functional diversity in ecosystem processes. Additionally, the role of evenness  confirm the review of @Zhang2012 who highlighted the role of evenness in productivity and thus resilience following our hypothesis. Finally, species and functional richnesses are not directly increasing resilience. But increased species and functional richnesses will increase chance for high functional diversity through the sampling effect [@Loreau1998]. An higher sampling of regional species pool will allow a greater chance to pick more functionally diverse species.

## Complementarity and selection insure forest resilience

We found that complementary effect was insuring forest resilience in the beginning of forest successions. We interpreted this results as the consequence of facilitation processes. As the only ressource simulated by TROLL is the light, the main facilitation will be light shading of post-pioneer species by pioneer species in disturbance gaps. Our results confirm the study of @Morin2011 who also highlighted the importance of facilitation through light shading in forest resilience. But the complementarity effect is reducing through time, to let the selection effect insure forest resilience due to an inforced dominance of more productive species. The diminishing of complementarity effect is due to competitive selection though time in gaps succession. But the study scale matters as shown by @Chisholm2013. Here we look at processes to a 16 ha scale. We do not have topography reducing micro-environment effects, but @Chisholm2013 results suggest that complementarity will be stronger at smaller scale and could explain its low value after forest recovery. Finally, our findings confirm results of @Tobner2016 realized on experimental forests of 4 years in low diverse forest of Canada. They also found that selection effect was greater than complementarity in most of the cases. In the case of selective logging the complementarity effect will thus be the major effect between two cutting cycles due to the cycle length (several decades in guyana shield). High forest diversity with important species complementarity through increased functional diversity is thus an advantage for forest recovery between two cutting cycles in order to maintain both productive ecosystem and sustainable management.

## Conclusion

We used closed forest system simulated with TROLL forest model to evaluate the role and mechanisms of biodiversity in tropical forest resilience to disturbance. We found that diversity improved forest resilience together with productivity [@Liang2016]. Additionally we found that complementarity between species was insuring forest recovery in forest succession start with facilitation, before more productive species dominate the forest and insure forest recovery. Our results advocate for sustainable selective logging against monoculture stand: high diversity will increase forest resilience and thus improve logging cycles. Even if monoculture stand are naturalized they will not reach mature forest diversity, and consequently they will not reach its natural high resilience. But on the other hand selective logging in tropical forest needs to be sustainable, if not the diversity will slowly decrease after each cycles degrading forest ecosystem functions, and resilience will decrease due to negative feedbacks. @Zimmerman2012 criticized the state of sylviculture in tropics, suggesting that "we have not been able to reconcile these opposing biological and economic forces". Still, they advocates for a possibility of sustainable tropical logging, already existing in small-scale, that will need proper funding from the internationnal communtiy. This view correspond to the high resilience of tropical forest hyperdiverse systems, we were able to show, and let hope for a future sustainable selective logging in tropical forests.
